"""Convert the Field Tech training corpus (PDF + DOCX) into a single TS module.

Usage:
    python scripts/build-knowledge.py
    python scripts/build-knowledge.py --source "path/to/training folder"

Produces src/knowledge.ts which exports the corpus as a const string.
The Worker imports it and sends it to Anthropic as a cached system block.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

try:
    import pymupdf4llm
except ImportError:
    sys.exit("Missing pymupdf4llm. Run: pip install -r scripts/requirements.txt")

try:
    import mammoth
except ImportError:
    sys.exit("Missing mammoth. Run: pip install -r scripts/requirements.txt")


DEFAULT_SOURCE = (
    Path.home()
    / "OneDrive - RJ Machine"
    / "Documents"
    / "Claude"
    / "Projects"
    / "Field Tech Training Guides and Exams"
)

OUT_FILE = Path(__file__).resolve().parent.parent / "src" / "knowledge.ts"

# Files to skip — not useful as text context.
SKIP_EXACT = {"CLAUDE.md"}
SKIP_SUFFIXES = {".png", ".jpg", ".jpeg", ".gif", ".xlsx", ".html"}
SKIP_DIRS = {"scripts", ".git", "node_modules"}


def convert_pdf(path: Path) -> str:
    return pymupdf4llm.to_markdown(str(path))


def convert_docx(path: Path) -> str:
    with path.open("rb") as f:
        result = mammoth.convert_to_markdown(f)
        return result.value


def collect_docs(source: Path) -> list[tuple[str, str]]:
    """Return list of (display_title, markdown_body)."""
    out: list[tuple[str, str]] = []
    for path in sorted(source.rglob("*")):
        if not path.is_file():
            continue
        if any(part in SKIP_DIRS for part in path.relative_to(source).parts):
            continue
        if path.name in SKIP_EXACT:
            continue
        if path.suffix.lower() in SKIP_SUFFIXES:
            continue

        title = path.stem
        try:
            if path.suffix.lower() == ".pdf":
                body = convert_pdf(path)
            elif path.suffix.lower() == ".docx":
                body = convert_docx(path)
            else:
                print(f"  SKIP (unknown): {path.name}", file=sys.stderr)
                continue
        except Exception as e:
            print(f"  ERROR: {path.name}: {e}", file=sys.stderr)
            continue

        if not body.strip():
            print(f"  SKIP (empty): {path.name}", file=sys.stderr)
            continue

        out.append((title, body.strip()))
        print(f"  OK   ({len(body):>7,} chars): {path.name}")

    return out


def build_corpus(docs: list[tuple[str, str]]) -> str:
    parts: list[str] = []
    for title, body in docs:
        parts.append(f"\n\n=== SOURCE: {title} ===\n\n{body}")
    return "".join(parts).strip()


def write_module(corpus: str) -> None:
    OUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    # JSON.stringify-style escape: handles backticks, backslashes, dollar signs, newlines.
    escaped = json.dumps(corpus)
    contents = (
        "// AUTO-GENERATED by scripts/build-knowledge.py — DO NOT EDIT BY HAND.\n"
        "// Regenerate with: npm run build-knowledge\n\n"
        f"export const KNOWLEDGE_BASE: string = {escaped};\n"
    )
    OUT_FILE.write_text(contents, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--source",
        type=Path,
        default=DEFAULT_SOURCE,
        help=f"Source folder (default: {DEFAULT_SOURCE})",
    )
    args = parser.parse_args()

    if not args.source.exists():
        sys.exit(f"Source folder not found: {args.source}")

    print(f"Reading from: {args.source}")
    docs = collect_docs(args.source)

    if not docs:
        sys.exit("No documents converted. Check source folder.")

    corpus = build_corpus(docs)
    write_module(corpus)

    print()
    print(f"Wrote {OUT_FILE}")
    print(f"  Documents: {len(docs)}")
    print(f"  Characters: {len(corpus):,}")
    print(f"  Approx tokens: {len(corpus) // 4:,} (rough estimate)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
